name: Process boot.img from URL

on:
  workflow_dispatch: # Allow manual triggering of the workflow
    inputs:
      boot_img_url:
        description: "URL to download the boot.img file"
        required: true
        type: string

jobs:
  process-boot-img:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download boot.img from the provided URL
      - name: Download boot.img
        run: |
          curl -L -o boot.img "${{ github.event.inputs.boot_img_url }}"
          if [ ! -f "boot.img" ]; then
            echo "Failed to download boot.img. Exiting."
            exit 1
          fi

      # Step 3: Ensure magiskboot is executable and process boot.img
      - name: Process boot.img
        run: |
          # Ensure magiskboot is executable
          chmod +x magiskboot

          # Run magiskboot and capture output
          OUTPUT=$(./magiskboot unpack boot.img 2>&1)
          echo "$OUTPUT"

          # Extract the KERNEL_FMT line from the output
          KERNEL_FMT=$(echo "$OUTPUT" | grep 'KERNEL_FMT' | awk -F'[][]' '{print $2}' || echo "UNKNOWN or incorrect boot.img link")
          echo "Found Kernel Format: $KERNEL_FMT"

          # Validate the extracted kernel format
          if [ "$KERNEL_FMT" = "UNKNOWN or incorrect boot.img link" ] || [ -z "$KERNEL_FMT" ]; then
            echo "Kernel format not found or incorrect boot.img link. Exiting."
            exit 1
          fi

          # Create a file named after the kernel format
          echo "$KERNEL_FMT" > "${KERNEL_FMT}.txt"

          # Save the file name to GITHUB_ENV
          echo "KERNEL_FILE=${KERNEL_FMT}.txt" >> $GITHUB_ENV

      # Step 4: Commit and Push the New File
      - name: Commit and Push
        env:
          FILE_NAME: ${{ env.KERNEL_FILE }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add the new file
          git add "$FILE_NAME"
          
          # Commit the change
          git commit -m "found kernel format: $FILE_NAME"
          
          # Push the change
          git push
